webdriver: firefox

timeouts:
  short: 8
  medium: 30
  long: 120

cal_net:
  base_url: https://auth-test.berkeley.edu

suite_c:
  base_url: https://calcentral-col-qa-01.ist.berkeley.edu
  lti_key: secret
  lti_secret: secret
  poller_retries: 20

canvas:
  base_url: https://ucberkeley.test.instructure.com
  sub_account: secret
  create_course_site_tool: secret
  course_add_user_tool: secret
  course_captures_tool: secret
  rosters_tool: secret

calcentral:
  base_url: https://calcentral-qa.berkeley.edu
  basic_auth_password: secret
  admin_uid: secret

users:
  super_admin_username: secret
  super_admin_password: secret
  super_admin_uid: secret
  ets_qa_username: secret
  ets_qa_password: secret
  test_user_password: secret
